fixing docker action

diff --git a/.github/workflows/docker-check.yml b/.github/workflows/docker-check.yml
--- a/.github/workflows/docker-check.yml
+++ b/.github/workflows/docker-check.yml
@@ -13,4 +13,4 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Docker compose up, wait for services to be healthy, otherwise fail after a timeout
-        run: docker-compose up -d --build && timeout 300s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
+        run: ./generate_env_file.sh ; docker-compose up -d --build && timeout 300s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
