fixing

diff --git a/.github/workflows/docker-check.yml b/.github/workflows/docker-check.yml
--- a/.github/workflows/docker-check.yml
+++ b/.github/workflows/docker-check.yml
@@ -7,10 +7,14 @@ on:
     branches: ["main"]
 
 jobs:
-  build:
+  build_and_test:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3
+      - name: Generate env file
+        run: ./generate_env_file.sh
+      - name: Build containers and compose up
+        run: docker-compose up -d --build
       - name: Docker compose up, wait for services to be healthy, otherwise fail after a timeout
-        run: ./generate_env_file.sh ; docker-compose up -d --build && timeout 300s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
+        run: timeout 600s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "Current status:" && docker ps | grep "(healthy)" && echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
