fix

diff --git a/.github/workflows/docker-check.yml b/.github/workflows/docker-check.yml
--- a/.github/workflows/docker-check.yml
+++ b/.github/workflows/docker-check.yml
@@ -14,7 +14,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: Generate env file
         run: ./generate_env_file.sh
-      - name: Build
-        run: docker-compose up --build
-      # - name: Build containers and compose up, docker compose up, wait for services to be healthy, otherwise fail after a timeout
-      #   run: docker-compose up -d --build && timeout 300s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "Current status:" && docker ps | grep "(healthy)" && echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
+      - name: Build and compose up
+        run: docker-compose up -d --build
+      - name: Wait for services to be healthy, otherwise fail after a 5 minutes timeout
+        run: timeout 300s bash -c 'until test `docker ps | grep "(healthy)" | wc -l` -eq 3 && echo "All 3 services are healthy, OK" && exit 0 || echo "Current status:" && docker ps | grep "(healthy)" && echo "All 3 services are NOT healthy yet, retrying in 10 seconds..." && /dev/null 2> /dev/null ; do sleep 10; done' ; echo "All 3 services are NOT healthy, FAIL" && exit 1
